**101 Numpy Practice Question**

1. Import numpy as np and see the version

In [ ]:
import numpy as np
np.version.version

'1.22.4'

2. How to create a 1D array?

In [ ]:
# np.array((2,3,4,5,6))
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

In [ ]:
1# np.full((3, 3), True, dtype=bool)
2# np.ones(dtype=bool,shape=(3,3))
3#
import random
array = []
for _ in range(10):
    num = random.randint(0,1)
    array.append(num)
nump_array = np.array(array,dtype='bool')
print(nump_array)

[ True False False  True False  True  True False  True  True]


4. How to extract items that satisfy a given condition from 1D array?
Q. Extract all odd numbers

In [ ]:
a = np.random.randint(100,size=(5,5))
print(a)
a[a % 2 != 0]

[[61 67 41 56 59]
 [23 97 41 68 17]
 [96 69 90 38 22]
 [97 99 83 33 62]
 [55 84 58 56 40]]


array([61, 67, 41, 59, 23, 97, 41, 17, 69, 97, 99, 83, 33, 55])

5. How to replace items that satisfy a condition with another value in numpy array?
Q. Replace all odd numbers in arr with -1

In [ ]:
a = np.random.randint(100,size=(5,5))
print(a)
# np.where(a % 2 == 0, a, -1)
a[a % 2 != 0] = -1
print(a)

[[43 72 69  9 98]
 [16 70 43 62 48]
 [24 91 87 91 60]
 [12 63  5 56 36]
 [75 50 72  2 87]]
[[-1 72 -1 -1 98]
 [16 70 -1 62 48]
 [24 -1 -1 -1 60]
 [12 -1 -1 56 36]
 [-1 50 72  2 -1]]


6. How to replace items that satisfy a condition without affecting the original array?
Q. Replace all odd numbers in arr with -1 without changing arr

In [ ]:
a = np.random.randint(100,size=(5,5))
print(a)
print(np.where(a % 2 == 0, a, -1))
print(a)

[[68 78 65 50 35]
 [63  3 51 60  0]
 [ 0 65 37  9 37]
 [60 47  9 87 91]
 [16 61 21 48 93]]
[[68 78 -1 50 -1]
 [-1 -1 -1 60  0]
 [ 0 -1 -1 -1 -1]
 [60 -1 -1 -1 -1]
 [16 -1 -1 48 -1]]
[[68 78 65 50 35]
 [63  3 51 60  0]
 [ 0 65 37  9 37]
 [60 47  9 87 91]
 [16 61 21 48 93]]


7. How to reshape an array?
Q. Convert a 1D array to a 2D array with 2 rows

In [ ]:
a = np.arange(10)
# b = a.reshape(2,5)
b = a.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# c = np.concatenate((a,b), axis = 0)
c = np.vstack([a, b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# c = np.concatenate((a,b), axis = 1)
c = np.hstack([a, b])
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?

Input: a = np.array([1,2,3])

Desired Output: #> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a = np.array([1,2,3])
# b = np.repeat(a,3)
# c = np.tile(a,3)
# np.concatenate((b,c))
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?

Input: 
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output: array([2, 4])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

12. How to remove from one array those items that exist in another?

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Desired Output: 
array([1,2,3,4])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
1# c = np.in1d(a,b)
# a[~c]

2#
# From 'a' remove all of 'b'
np.setdiff1d(a,b)
#> array([1, 2, 3, 4])

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:(array([1, 3, 5, 7]),)

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

14. How to extract all numbers between a given range from a numpy array? Q. Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output: (array([6, 9, 10]),)

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
# b = np.where((a <= 10) & (a >= 5))
# a[b]
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

15. How to make a python function that handles scalars to work on numpy arrays? Q. Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

a = np.array([5, 7, 9, 8, 6, 4, 5])

b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [ ]:
def maxx(a,b):
  return np.maximum(a,b)

In [ ]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
maxx(1,5)

5

16. How to swap two columns in a 2d numpy array?


In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. How to swap two rows in a 2d numpy array?


In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,0,2],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

18. How to reverse the rows of a 2D array?

In [ ]:
arr = np.arange(9).reshape(3,3)
# np.flip(arr, axis = 0)
# arr[::-1]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

19. How to reverse the columns of a 2D array?

In [ ]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]
np.flip(arr, axis = 1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. How to create a 2D array containing random floats between 5 and 10?

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [ ]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[5.81421981 8.73820279 8.8180842 ]
 [7.25935392 5.42422342 6.76310966]
 [9.50333388 6.25280617 5.96881859]
 [8.81554405 7.29754857 6.94954821]
 [6.66367416 8.11743632 5.64576809]]


21. How to print only 3 decimal places in python numpy array?

Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [ ]:
rand_arr = np.random.random((5,3)).round(3)
rand_arr

array([[0.539, 0.79 , 0.124],
       [0.627, 0.036, 0.418],
       [0.157, 0.585, 0.218],
       [0.8  , 0.894, 0.181],
       [0.14 , 0.879, 0.622]])

22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [ ]:
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress=True, precision=6)  # precision is optional
print(rand_arr)

[[0.00065  0.000264 0.000458]
 [0.000317 0.00093  0.000941]
 [0.000474 0.000253 0.00007 ]]
[[0.00065  0.000264 0.000458]
 [0.000317 0.00093  0.000941]
 [0.000474 0.000253 0.00007 ]]


23. How to limit the number of items printed in output of numpy array?

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [ ]:
a = np.arange(15)
np.set_printoptions(threshold=3)
a

array([ 0,  1,  2, ..., 12, 13, 14])

24. How to print the full numpy array without truncating

np.set_printoptions(threshold=6)
a = np.arange(15)
a

#> array([ 0,  1,  2, ..., 12, 13, 14])


Desired Output:

a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
from sys import maxsize
np.set_printoptions(threshold=8)
a = np.arange(20)
a

np.set_printoptions(threshold=maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

Q. Import the iris dataset keeping the text intact.

In [ ]:
arr = np.loadtxt("/content/Iris.csv",delimiter=",", dtype=str)
arr[:3]

array([['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
        'PetalWidthCm', 'Species'],
       ['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa']], dtype='<U15')

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=object)
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

26. How to extract a particular column from 1D array of tuples?

Q. Extract the text column species from the 1D iris imported in previous question.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'


iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)



In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
species = np.array([row[4] for row in iris_1d])
species[:5]

<ipython-input-83-f971d5fc7670>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

27. How to convert a 1d array of tuples to a 2d numpy array?

Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Solution:
# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

# Alt Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

<ipython-input-48-3858d13609a8>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

28. How to compute the mean, median, standard deviation of a numpy array?

Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=float, usecols=(0))
print('Mean', np.mean(iris).round(3))
print('Median', np.median(iris).round(3))
print('Standard Deviation', np.std(iris).round(3))

Mean 5.843
Median 5.8
Standard Deviation 0.825


29. How to normalize an array so the values range exactly between 0 and 1?

Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
min, max = sepallength.min(), sepallength.max()
normalized = (sepallength - min)/(max - min)
normalized

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

30. How to compute the softmax score?

Q. Compute the softmax score of sepallength.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)
softmax(sepallength).round(3)

array([0.002, 0.002, 0.001, 0.001, 0.002, 0.003, 0.001, 0.002, 0.001,
       0.002, 0.003, 0.002, 0.002, 0.001, 0.004, 0.004, 0.003, 0.002,
       0.004, 0.002, 0.003, 0.002, 0.001, 0.002, 0.002, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.002, 0.003, 0.002, 0.003, 0.002, 0.002,
       0.003, 0.002, 0.001, 0.002, 0.002, 0.001, 0.001, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.003, 0.002, 0.015, 0.008, 0.013, 0.003,
       0.009, 0.004, 0.007, 0.002, 0.01 , 0.002, 0.002, 0.005, 0.005,
       0.006, 0.004, 0.011, 0.004, 0.004, 0.007, 0.004, 0.005, 0.006,
       0.007, 0.006, 0.008, 0.01 , 0.012, 0.011, 0.005, 0.004, 0.003,
       0.003, 0.004, 0.005, 0.003, 0.005, 0.011, 0.007, 0.004, 0.003,
       0.003, 0.006, 0.004, 0.002, 0.004, 0.004, 0.004, 0.007, 0.002,
       0.004, 0.007, 0.004, 0.016, 0.007, 0.009, 0.027, 0.002, 0.02 ,
       0.011, 0.018, 0.009, 0.008, 0.012, 0.004, 0.004, 0.008, 0.009,
       0.03 , 0.03 , 0.005, 0.013, 0.004, 0.03 , 0.007, 0.011, 0.018,
       0.007, 0.006,

31. How to find the percentile scores of a numpy array?

Q. Find the 5th and 95th percentile of iris's sepallength

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength,[5,95])

array([4.6  , 7.255])

32. How to insert values at random positions in an array?

Q. Insert np.nan values at 20 random positions in iris_2d dataset

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
# iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
# print(iris_1d.shape)
# print(iris_2d.shape)
# Method 1
# i, j = np.where(iris_2d)

# i, j contain the row numbers and column numbers of 600 elements of iris_x
# np.random.seed(100)
# iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

# Method 2
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


33. How to find the position of missing values in numpy array?

Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
index = np.where(np.isnan(iris_2d[:,0]))
print(index)
len(index[0])

(array([ 46,  48,  66,  69,  71, 119, 124]),)


7

In [ ]:
if (np.nan == float('nan')):
  print('True')
else:
  print('False')

False


34. How to filter a numpy array based on two or more conditions?

Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[(iris_2d[:,0] < 5) & (iris_2d[:,2] > 1.5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

35. How to drop rows that contain a missing value from a numpy array?

Q. Select the rows of iris_2d that does not have any nan value.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

# Method 2: (By Rong)
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

36. How to find the correlation between two columns of a numpy array?

Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

cor = np.corrcoef(iris_2d[:,0],iris_2d[:, 2])
cor[0,1]

0.8717541573048718

37. How to find if a given array has any null values?

Q. Find out if iris_2d has any missing values.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# np.any(np.isnan(iris_2d))
np.isnan(iris_2d).any()

False

38. How to replace all missing values with 0 in a numpy array?

Q. Replace all ccurrences of nan with 0 in numpy array

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0

39. How to find the count of unique values in a numpy array?

Q. Find the unique values and the count of unique values in iris's species

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
np.unique(iris[:,4], return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([50, 50, 50]))

40. How to convert a numeric to a categorical (text) array?

Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

Less than 3 --> 'small'
3-5 --> 'medium'
'>=5 --> 'large'

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal = iris[:,2].astype('float')
def check(val):
  if val < 3:
    return 'small'
  elif (val >= 3 and val < 5):
    return 'medium'
  elif val >= 5:
    return 'large'
  else:
    return 'nan'
arr = [check(row) for row in petal]


41. How to create a new column from existing columns of a numpy array?

Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3


# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris_2d, volume])


In [ ]:
import numpy as np

42. How to do probabilistic sampling in numpy?

Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

In [ ]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species column
species = iris[:, 4]

# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])

# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

#> (array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'], dtype=object), array([77, 37, 36]))


(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([77, 37, 36]))


43. How to get the second largest value of an array when grouped by another array?

Q. What is the value of second longest petallength of species setosa

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species and petal length columns
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

# Get the second last value
np.unique(np.sort(petal_len_setosa))[-2]
#> 1.7


1.7

44. How to sort a 2D array by a column

Q. Sort the iris dataset based on sepallength column.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

index = iris[:,0].astype('float').argsort()
iris[index]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4

45. How to find the most frequent value in a numpy array?

Q. Find the most frequent value of petal length (3rd column) in iris dataset.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# desi method
unique = np.unique(iris[:,2].astype('float'),return_counts=True)
maxindex = unique[1].argmax()
unique[0][maxindex]

# 2 method
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


46. How to find the position of the first occurrence of a value greater than a given value?

Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere(iris[:,3].astype('float') > 1)[0]

array([50])

47. How to replace all values greater than a given value to a given cutoff?

Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a,a_min=10,a_max=30)


# Solution 2: Using np.where
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


48. How to get the positions of top n values from a numpy array?

Q. Get the positions of top 5 maximum values in a given array a.

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
np.flip(np.argsort(a))[:5]

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]


array([15, 10,  3,  7, 18])

49. How to compute the row wise counts of all possible values in an array?

Q. Compute the counts of unique values row-wise.

Input:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

Desired Output:

> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

In [ ]:
# Input:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

50. How to convert an array of arrays into a flat 1d array?

Q. Convert array_of_arrays into a flat linear 1d array.

# Input:
arr1 = np.arange(3)

arr2 = np.arange(3,7)

arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])

Desired Output:

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])

# Solution 1
arr_2d = np.array([a for arr in array_of_arrays for a in arr])

# Solution 2:
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


<ipython-input-114-fd3637bb33c1>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3])


51. How to generate one-hot encodings for an array in numpy?

Q. Compute the one-hot encodings (dummy binary variables for each unique value in the array)

Input:

np.random.seed(101)

arr = np.random.randint(1,4, size=6)

arr

#> array([2, 3, 2, 2, 2, 1])

Output:

#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])

In [ ]:
# Input:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])

# Solution:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

one_hot_encodings(arr)
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])

# Method 2:
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

52. How to create row numbers grouped by a categorical variable?

Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
#> array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
#>        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
#>       dtype='<U15')

Desired Output:

#> [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small
count = 0
li = []
for i in range(len(species_small) -1):
  if (species_small[i] == species_small[i+1]):
    li.append(count)
    count +=1
  else:
    li.append(count)
    count = 0
li.append(count)
li

# # 2
# print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]

53. How to create groud ids based on a given categorical variable?

Q. Create group ids based on a given categorical variable. Use the following sample from iris species as input.

Input: Same as above

Desired Output:
#> [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)

count = 0
li = []
for i in range(len(species_small) -1):
  if (species_small[i] == species_small[i+1]):
    li.append(count)
  else:
    li.append(count)
    count +=1
li.append(count)
li


# output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]

# # Solution: For Loop version
# output = []
# uniqs = np.unique(species_small)

# for val in uniqs:  # uniq values in group
#     for s in species_small[species_small==val]:  # each element in group
#         groupid = np.argwhere(uniqs == s).tolist()[0][0]  # groupid
#         output.append(groupid)

# print(output)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']


[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

54. How to rank items in an array using numpy?

Input:

np.random.seed(10)

a = np.random.randint(20, size=10)

print(a)

#> [ 9  4 15  0 17 16 17  8  9  0]

Desired output:

[4 2 6 0 8 7 9 3 5 1]

In [ ]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

# Solution
print(a.argsort().argsort())

[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]


55. How to rank items in a multidimensional array using numpy?

Q. Create a rank array of the same shape as a given numeric array a.

#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]


Desired output:

#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]

In [ ]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


56. How to find the maximum value in each row of a numpy array 2d?

Q. Compute the maximum for each row in the given array.

In [ ]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Solution 1
np.amax(a, axis=1)

# Solution 2
np.apply_along_axis(np.max, arr=a, axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

57. How to compute the min-by-max for each row for a numpy array 2d?

Q. Compute the min-by-max for each row for given 2d numpy array.

In [ ]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
# Solution
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

58. How to find the duplicate records in a numpy array?

Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

#> Array: [0 0 3 0 2 4 2 2 2 2]

#> [False  True False  True False False  True  True  True  True]

In [ ]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
## Solution
# There is no direct function to do this as of 1.13.3

# Create an all True array
out = np.full(a.shape[0], True)

# Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False

print(out)

[False  True False  True False False  True  True  True  True]


61. How to drop all missing values from a numpy array?

Q. Drop all nan values from a 1D numpy array

In [ ]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

62. How to compute the euclidean distance between two arrays?

Q. Compute the euclidean distance between two arrays a and b.

In [ ]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# Solution
dist = np.linalg.norm(a-b)
dist

6.708203932499369

63. How to find all the local maxima (or peaks) in a 1d array?

Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

In [ ]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations
#> array([2, 5])

array([2, 5])

64. How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?

In [ ]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

# Solution
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


65. How to find the index of n'th repetition of an item in an array



In [ ]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Solution 1: List comprehension
[i for i, v in enumerate(x) if v == 1][n-1]

# Solution 2: Numpy version
np.where(x == 1)[0][n-1]
#> 8

8

66. How to convert numpy's datetime64 object to datetime's datetime object?

Q. Convert numpy's datetime64 object to datetime's datetime object

In [ ]:
# Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')

# Solution

dt64.tolist()
# or

from datetime import datetime
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

68. How to create a numpy array sequence given only the starting point, length and the step?

Q. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [ ]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

69. How to fill in missing dates in an irregular series of numpy dates?

Q. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

In [ ]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-24'), 2)
print(dates)

# For loop version -------
out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
output

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

70. How to create strides from a given 1D array?

Q. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

In [ ]:
arr = np.arange(15) 
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
